# Generated by Django 4.2.7 on 2025-11-19 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(help_text='ID del paciente (del microservicio de clínica)')),
                ('detection_date', models.DateField(help_text='Fecha de detección de la variante')),
                ('allele_frequency', models.DecimalField(decimal_places=4, help_text='Frecuencia alélica (VAF) entre 0 y 1', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='variants.geneticvariant')),
            ],
            options={
                'verbose_name': 'Reporte de Variante del Paciente',
                'verbose_name_plural': 'Reportes de Variantes de Pacientes',
                'db_table': 'patient_variant_reports',
                'ordering': ['-detection_date'],
                'unique_together': {('patient_id', 'variant', 'detection_date')},
            },
        ),
    ]
