# Generated by Django 4.2.7 on 2025-11-19 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(help_text='Cromosoma (ej: chr17)', max_length=10)),
                ('position', models.BigIntegerField(help_text='Posición en el cromosoma')),
                ('reference_base', models.CharField(help_text='Base de referencia (ej: A)', max_length=100)),
                ('alternate_base', models.CharField(help_text='Base alternativa (ej: G)', max_length=100)),
                ('impact', models.CharField(choices=[('MISSENSE', 'Missense'), ('FRAMESHIFT', 'Frameshift'), ('NONSENSE', 'Nonsense'), ('SILENT', 'Silent'), ('SPLICE_SITE', 'Splice Site')], help_text='Impacto de la variante', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='genes.gene')),
            ],
            options={
                'verbose_name': 'Variante Genética',
                'verbose_name_plural': 'Variantes Genéticas',
                'db_table': 'genetic_variants',
                'ordering': ['chromosome', 'position'],
                'unique_together': {('gene', 'chromosome', 'position', 'reference_base', 'alternate_base')},
            },
        ),
    ]
