apiVersion: v1
kind: ConfigMap
metadata:
  name: clinica-config
  namespace: genosentinel
data:
  PORT: "3001"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  DB_DATABASE: "genosentinel_clinica"
---
apiVersion: v1
kind: Secret
metadata:
  name: clinica-secrets
  namespace: genosentinel
stringData:
  DB_PASSWORD: "1234"
