apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: genosentinel
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  DB_DATABASE: "genosentinel_auth"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: genosentinel
stringData:
  DB_PASSWORD: "1234"
