apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-auth
  namespace: genosentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-auth
  template:
    metadata:
      labels:
        app: microservicio-auth
    spec:
      containers:
        - name: microservicio-auth
          image: genosentinel/microservicio-auth:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CLINICA_BASE_URL
              value: "http://microservicio-clinica:3001"
            - name: GENOMICA_BASE_URL
              value: "http://microservicio-genomica:8000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_USERNAME
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: DB_PASSWORD
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /gateway/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /gateway/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
