apiVersion: v1
kind: Service
metadata:
  name: microservicio-genomica
  namespace: genosentinel
spec:
  type: ClusterIP
  selector:
    app: microservicio-genomica
  ports:
    - name: http
      port: 8000
      targetPort: 8000
