apiVersion: v1
kind: Service
metadata:
  name: microservicio-auth
  namespace: genosentinel
spec:
  type: NodePort
  selector:
    app: microservicio-auth
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
