# Generated by Django 4.2.7 on 2025-11-19 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(help_text='Símbolo del gen (ej: BRCA1)', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Nombre completo del gen', max_length=255)),
                ('function_summary', models.TextField(help_text='Resumen de la función del gen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gen',
                'verbose_name_plural': 'Genes',
                'db_table': 'genes',
                'ordering': ['symbol'],
            },
        ),
    ]
